library(corrplot)
library(dplyr)
library(tidyr)
library(stringr)
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
data <- read.csv("regression_train_loan.csv")
head(data)
summary(data)
data <- drop_na(data, int_rate)
# convert term to numeric
data$term = str_replace(data$term," months","")
data$term = as.numeric(data$term)
# convert grade to numeric
unique(data$grade)
data$grade <- ifelse(data$grade == "A", 1, data$grade)
data$grade <- ifelse(data$grade == "B", 2, data$grade)
data$grade <- ifelse(data$grade == "C", 3, data$grade)
data$grade <- ifelse(data$grade == "D", 4, data$grade)
data$grade <- ifelse(data$grade == "E", 5, data$grade)
data$grade <- ifelse(data$grade == "F", 6, data$grade)
data$grade <- ifelse(data$grade == "G", 7, data$grade)
data$grade = as.numeric(data$grade)
# convert sub_grade to numeric - the letter always matches the one in grade
data$sub_grade = str_replace(data$sub_grade,"[:alpha:]","")
data$sub_grade = as.numeric(data$sub_grade)
# convert emp_length to numeric
unique(data$emp_length)
data$emp_length = str_replace(data$emp_length," years","")
data$emp_length = str_replace(data$emp_length," year","")
data$emp_length = str_replace(data$emp_length,"n/a","-1") 
data$emp_length = str_replace(data$emp_length,"< 1","0") 
data$emp_length = str_replace(data$emp_length,"\\+","") 
data$emp_length = as.numeric(data$emp_length)
# convert home_ownership to numeric
unique(data$home_ownership)
data$home_ownership <- ifelse(data$home_ownership == "NONE", 0, data$home_ownership)
data$home_ownership <- ifelse(data$home_ownership == "OTHER", 1, data$home_ownership)
data$home_ownership <- ifelse(data$home_ownership == "ANY", 2, data$home_ownership)
data$home_ownership <- ifelse(data$home_ownership == "MORTGAGE", 3, data$home_ownership)
data$home_ownership <- ifelse(data$home_ownership == "RENT", 4, data$home_ownership)
data$home_ownership <- ifelse(data$home_ownership == "OWN", 5, data$home_ownership)
data$home_ownership = as.numeric(data$home_ownership)
# convert verification_status to numeric
unique(data$verification_status)
data$verification_status <- ifelse(data$verification_status == "Not Verified", 0, data$verification_status)
data$verification_status <- ifelse(data$verification_status == "Source Verified", 1, data$verification_status)
data$verification_status <- ifelse(data$verification_status == "Verified", 2, data$verification_status)
data$verification_status = as.numeric(data$verification_status)
# convert loan_status to numeric
unique(data$loan_status)
data$loan_status <- ifelse(data$loan_status == "Current", 0, data$loan_status)
data$loan_status <- ifelse(grepl("Charged Off",data$loan_status), 1, data$loan_status)
data$loan_status <- ifelse(grepl("Fully Paid",data$loan_status), 2, data$loan_status)
data$loan_status <- ifelse(data$loan_status == "Issued", 3, data$loan_status)
data$loan_status <- ifelse(data$loan_status == "In Grace Period", 4, data$loan_status)
data$loan_status <- ifelse(data$loan_status == "Late (31-120 days)", 5, data$loan_status)
data$loan_status <- ifelse(data$loan_status == "Default", 6, data$loan_status)
data$loan_status <- ifelse(data$loan_status == "Late (16-30 days)", 6, data$loan_status)
data$loan_status = as.numeric(data$loan_status)
# convert pymnt_plan to numeric
unique(data$pymnt_plan)
data$pymnt_plan <- ifelse(data$pymnt_plan == "n", 0, data$pymnt_plan)
data$pymnt_plan <- ifelse(data$pymnt_plan == "y", 1, data$pymnt_plan)
data$pymnt_plan = as.numeric(data$pymnt_plan)
# convert purpose to numeric
unique(data$purpose)
data$purpose <- ifelse(data$purpose == "credit_card", 0, data$purpose)
data$purpose <- ifelse(data$purpose == "debt_consolidation", 1, data$purpose)
data$purpose <- ifelse(data$purpose == "home_improvement", 2, data$purpose)
data$purpose <- ifelse(data$purpose == "vacation", 3, data$purpose)
data$purpose <- ifelse(data$purpose == "other", 4, data$purpose)
data$purpose <- ifelse(data$purpose == "major_purchase", 5, data$purpose)
data$purpose <- ifelse(data$purpose == "medical", 6, data$purpose)
data$purpose <- ifelse(data$purpose == "car", 7, data$purpose)
data$purpose <- ifelse(data$purpose == "wedding", 8, data$purpose)
data$purpose <- ifelse(data$purpose == "small_business", 9, data$purpose)
data$purpose <- ifelse(data$purpose == "renewable_energy", 10, data$purpose)
data$purpose <- ifelse(data$purpose == "moving", 11, data$purpose)
data$purpose <- ifelse(data$purpose == "house", 12, data$purpose)
data$purpose <- ifelse(data$purpose == "educational", 13, data$purpose)
data$purpose = as.numeric(data$purpose)
# convert zip_code to numeric
unique(data$zip_code)
data$zip_code = str_replace(data$zip_code,"xx","00") 
data$zip_code = as.numeric(data$zip_code)
# convert addr_state to numeric
unique(data$application_type)
data$application_type <- ifelse(data$application_type == "INDIVIDUAL", 0, data$application_type)
data$application_type <- ifelse(data$application_type == "JOINT", 1, data$application_type)
data$application_type = as.numeric(data$application_type)
# convert verification_status_joint to numeric
unique(data$verification_status_joint)
data$verification_status_joint <- ifelse(data$verification_status_joint == "", -1, data$verification_status_joint)
data$verification_status_joint <- ifelse(data$verification_status_joint == "Not Verified", 0, data$verification_status_joint)
data$verification_status_joint <- ifelse(data$verification_status_joint == "Source Verified", 1, data$verification_status_joint)
data$verification_status_joint <- ifelse(data$verification_status_joint == "Verified", 2, data$verification_status_joint)
data$verification_status_joint = as.numeric(data$verification_status_joint)
# convert verification_status_joint to numeric
unique(data$initial_list_status)
data$initial_list_status <- ifelse(data$initial_list_status == "w", 0, data$initial_list_status)
data$initial_list_status <- ifelse(data$initial_list_status == "f", 1, data$initial_list_status)
data$initial_list_status = as.numeric(data$initial_list_status)
# setup data fram with only numeric columns
num_data <- select_if(data, is.numeric)  
# drop columns with NA
num_data <- na.omit(num_data)
# drop columns with primaryly 0
num_data <- subset(num_data, select = -c(total_rec_late_fee,recoveries,collection_recovery_fee,collections_12_mths_ex_med,pymnt_plan,acc_now_delinq) )

# plot correlation
#corrplot(cor(select(num_data,-c(int_rate))), type = "upper", order = "hclust", tl.col = "black", tl.srt = 45)
